"""Direct unit coverage for pipeline/pdf/pymupdf_engine.py's private
_group_lines_by_x0() - the column-split step extract_blocks() and
extract_ico_header_text() both build on.

02.09.2026 (Michael, real document "2133 XLMFOMO.pdf", uploaded to
diagnose "keine PDFs gefunden" with the new date filter): a date line
("June 18, 2026") and an "ICO Telegram Write Up: Post Link" line went
missing from extract_ico_header_text()'s result entirely, even though
both sit in the very same PyMuPDF block as "Issuer Address" further
down. Root cause, confirmed by dumping that PDF's raw block/line
structure by hand: the blank line PyMuPDF's own PDF (generated by
whatever tool Michael's ICO template comes from - NOT this project's
insert_text()) emits right after a hyperlink run sits at x0≈553 (the
page's right edge) even though every real text line around it sits at
x0≈43 - _group_lines_by_x0()'s old version compared EVERY line's x0
against the running min/max, blank or not, so that one stray blank
fractured an otherwise single-column block into 3 unrelated groups; the
date/Telegram-link lines ended up alone in a group with no
FIRST_PAGE_ANCHOR_TERMS match of their own, which
_split_first_page_metadata() then returns unchanged - and
extract_ico_header_text() only ever keeps a group whose split actually
found the anchor, so that whole group was silently dropped.

This tests _group_lines_by_x0() directly (unlike this project's usual
black-box-through-a-real-PDF style) because the exact PyMuPDF quirk
that produces such a stray-blank-at-an-outlier-x0 line turned out to be
tied to whatever tool generated Michael's PDF - reproducing it through
page.insert_text() proved unreliable (confirmed by hand: PyMuPDF's own
block detector kept merging/dropping/re-splitting the synthetic outlier
line in ways that didn't match the real file), while the actual fix
lives entirely inside this one function and is trivial to pin down
directly with hand-built line dicts shaped like PyMuPDF's real ones
(only "bbox" and "spans"/"text" are ever read).
tests/test_pdf_ico_header_search.py additionally covers the fix at the
extract_ico_header_text() level for a shape page.insert_text() CAN
reproduce faithfully.
"""
from __future__ import annotations

from pipeline.pdf.pymupdf_engine import _group_lines_by_x0


def _line(text: str, x0: float) -> dict:
    return {"bbox": (x0, 0.0, x0 + 10.0, 10.0), "spans": [{"text": text}]}


def test_a_blank_line_at_an_outlier_x0_does_not_split_the_group_around_it() -> None:
    # Michael's exact real shape: two real lines, then the stray blank
    # at x0≈553 (the outlier), then more real lines including the
    # anchor - must all stay ONE group.
    lines = [
        _line("June 18, 2026", 42.6),
        _line(" ", 42.6),
        _line("ICO Telegram Write Up: Post Link", 42.6),
        _line(" ", 552.94),  # the real-world outlier, see module docstring
        _line(" ", 42.6),
        _line("Domain: example.org", 42.6),
        _line("Issuer Address:", 42.6),
    ]
    groups = _group_lines_by_x0(lines, threshold=50.0)
    assert groups == [lines]


def test_a_leading_blank_line_at_an_outlier_x0_does_not_poison_the_range() -> None:
    # The very first line being an outlier blank must not seed
    # current_min/current_max with its own meaningless x0 either.
    lines = [
        _line(" ", 552.94),
        _line("Real content", 42.6),
        _line("More real content", 42.6),
    ]
    groups = _group_lines_by_x0(lines, threshold=50.0)
    assert groups == [lines]


def test_several_blank_lines_at_different_outlier_positions_stay_harmless() -> None:
    lines = [
        _line("Real content", 42.6),
        _line(" ", 552.94),
        _line(" ", 999.0),
        _line("More real content", 42.6),
    ]
    groups = _group_lines_by_x0(lines, threshold=50.0)
    assert groups == [lines]


def test_two_genuinely_different_columns_of_real_content_still_split() -> None:
    # The actual, still-intended purpose of this function (see its
    # docstring/_COLUMN_SPLIT_THRESHOLD's comment) must be unaffected -
    # only BLANK lines are exempted from the split decision, real
    # content at a genuinely different x0 must still start a new group.
    lines = [
        _line("Left column line", 50.0),
        _line("Right column line", 300.0),
    ]
    groups = _group_lines_by_x0(lines, threshold=50.0)
    assert groups == [[lines[0]], [lines[1]]]


def test_a_blank_line_between_two_genuinely_different_columns_attaches_to_the_first() -> None:
    # A blank line still needs to end up SOMEWHERE - it attaches to
    # whichever group is open when it's reached, it just never causes
    # (or blocks) a split on its own.
    lines = [
        _line("Left column line", 50.0),
        _line(" ", 50.0),
        _line("Right column line", 300.0),
    ]
    groups = _group_lines_by_x0(lines, threshold=50.0)
    assert groups == [[lines[0], lines[1]], [lines[2]]]
