"""Orchestrates one PDF merge/insert job end-to-end (01.09.2026, Backlog.md
26.08.2026's "PDFs zusammenführen / PDFs zwischeneinfügen").

Deliberately NOT built on ui/document_job_common.py's/ui/models.py's
TranslationRequest/TranslationMode machinery, even though the backlog entry
that first floated this feature suggested wiring it in as just another
`mode` value there. TranslationRequest exists to drive a PAID translation
run (provider, target language, protected terms, the cost-analysis/
confirmation gate in ui/app.py's _analyze()/_start()) - none of that applies
here: merging spends no API budget, needs no provider, and RoadMap.md's own
"jeder kostenpflichtige Lauf braucht Analyse, Kostenschätzung und
ausdrückliche Bestätigung" Leitprinzip is about exactly the kind of run this
isn't. Forcing this through TranslationRequest would mean widening a
translation-specific validation/analysis/confirmation contract for a case
none of it fits, for every existing mode too. Kept as its own small module
instead - the actual merge mechanics live in
pipeline/pdf/pymupdf_engine.py's merge_pdfs()/MergeSourceSpec/PdfMergeStats
(see that function's docstring); this module adds the same
destination-safety layer ui/pdf_job.py's run_pdf_job() already has
(DestinationConflictError - same type, same checks) plus a small
pre-flight validate_merge_sources() the UI calls before ever opening a
file, so a typo'd path or an empty list surfaces as a clear message
instead of a raw exception from deep inside merge_pdfs().
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Sequence

from pipeline.pdf.pymupdf_engine import MergeSourceSpec, PdfMergeStats, merge_pdfs
from ui.document_job_common import DestinationConflictError


@dataclass
class MergeJobResult:
    output_path: Path
    stats: PdfMergeStats


def validate_merge_sources(sources: Sequence[MergeSourceSpec], destination: Path | None) -> list[str]:
    """Pre-flight checks the UI runs on every source-list/destination
    change to decide whether the Start button may be enabled - mirrors
    TranslationRequest.validation_errors()'s role for the translation
    modes, just without needing to open any file (page-range bounds are
    only checked once a file is actually opened, inside merge_pdfs()
    itself - re-checking bounds here would mean opening every source twice
    per keystroke in the page-range field).
    """
    errors: list[str] = []
    if not sources:
        errors.append("Mindestens eine Quelldatei hinzufügen.")
    for source in sources:
        if not source.path.is_file():
            errors.append(f"Datei nicht gefunden: {source.path}")
        elif source.path.suffix.lower() != ".pdf":
            errors.append(f"{source.path.name} ist keine PDF-Datei.")
    if destination is None or not str(destination).strip():
        errors.append("Zieldatei fehlt.")
    elif destination.suffix.lower() != ".pdf":
        errors.append("Zieldatei muss auf \".pdf\" enden.")
    return errors


def run_merge_job(
    sources: Sequence[MergeSourceSpec],
    destination: Path,
    progress_callback: Callable[[str], None] | None = None,
    should_cancel: Callable[[], bool] | None = None,
) -> MergeJobResult:
    """Run one full merge/insert job and return its result.

    Destination-safety check is narrower than run_pdf_job()'s: only
    "identical to one of the sources" is rejected (DestinationConflictError,
    same type run_pdf_job() uses) - a mistake the native Save dialog
    (ui/merge_dialog.py uses QFileDialog.getSaveFileName(), unlike the
    output-DIRECTORY pickers the translation modes use) can't catch on its
    own. An already-existing destination that ISN'T one of the sources is
    deliberately allowed to be overwritten here: unlike a translation run's
    destination (always auto-generated by safe_destination(), so silently
    reusing the same collided name would never be a real user's intent),
    merge's destination is the ONE path the user explicitly typed/picked -
    QFileDialog.getSaveFileName() already shows its own native "replace
    existing file?" confirmation before ever calling this function, so a
    second, silent refusal here would contradict a choice the user just
    confirmed.
    """
    destination = Path(destination)
    resolved_destination = destination.resolve()
    for source in sources:
        if source.path.resolve() == resolved_destination:
            raise DestinationConflictError(
                f"Zieldatei darf technisch nicht mit einer Quelldatei identisch sein: {source.path.name}"
            )

    stats = merge_pdfs(
        sources,
        destination,
        progress_callback=progress_callback,
        should_cancel=should_cancel,
    )
    return MergeJobResult(destination, stats)
